site_name: Apache Spark
site_url: https://dogradiwakar.github.io/
site_author: Diwakar Dogra
site_description: Demystifying inner-workings of Apache Spark


nav:
    - Home: index.md
    - Apache Spark:
        - GettingStarted: GettingStarted.md
    - About: about.md
theme:
  name: material