site_name: Apache Spark
site_url: https://dogradiwakar.github.io/
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Apache Spark


nav:
    - Home: index.md
    - About: about.md
theme:
  name: material