site_name: Apache Spark
site_url: https://dogradiwakar.github.io/
site_author: Diwakar Dogra
site_description: 

repo_name: docs
repo_url: https://github.com/dogradiwakar/docs
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Diwakar Dogra

   
    
nav:
  #- Home: index.md
  - Apache Spark:
    - Overview: Overview.md
    - GettingStarted: GettingStarted.md
    - Jupyter Notebook Integration: JupyterNotebookIntegration.md
    
    
    
theme:
  name: material
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

      
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Apache Spark
    spark_k8s: https://jaceklaskowski.github.io/spark-kubernetes-book
    spark_sql: https://jaceklaskowski.github.io/mastering-spark-sql-book
    structured_streaming: https://jaceklaskowski.github.io/spark-structured-streaming-book
  codahale:
    home: https://metrics.dropwizard.io/4.2.0
    api: https://www.javadoc.io/static/io.dropwizard.metrics/metrics-core/4.2.0
  hadoop:
    version: 3.3.1
    docs: https://hadoop.apache.org/docs/r3.3.1
    api: https://hadoop.apache.org/docs/r3.3.1/api
  jackson:
    api: https://fasterxml.github.io/jackson-databind/javadoc/2.12
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api
  scala:
    api: https://www.scala-lang.org/api/2.12.14
    docs: https://docs.scala-lang.org/
    spec: https://www.scala-lang.org/files/archive/spec/2.12
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
  spark:
    version: 3.2.0 (RC1)
    github: https://github.com/apache/spark/tree/v3.2.0-rc1